### ISSUE TITLE
A failing `CommitAsync` causes two session removals

### ISSUE THREAD

**Issue by fubar-coder** [FubarDevelopment/UnitOfWork#1]
```text
[2022-01-21 11:24:42 ERR]  The unit of work wasn't found - commit/rollback/dispose twice?
System.InvalidOperationException: The unit of work wasn't found - commit/rollback/dispose twice?
   at FubarDev.UnitOfWork.StatusManagement.DefaultStatusManager`1.Complete(TStatusItem statusItem, StatusItemResult result)
   at FubarDev.UnitOfWork.UnitOfWorkFactory`1.FinishAsync(UnitOfWorkStatusItem`1 statusItem, StatusItemResult status, CancellationToken cancellationToken)
   at FubarDev.UnitOfWork.TransactionalUnitOfWork`1.FinishAsync(StatusItemResult status, CancellationToken cancellationToken)
```

**Comment by fubar-coder** [comment]
Fixed in commit 4953d32d
